Running the pipeline locally - some adjusments
I've been trying to run the pipeline locally using the
test dataset but I bumped into a problem with Medaka.

I've made some tweaks to be able to run this locally:
- Added an ARM profile (to be able to run this in my macbook)
- Resource limits in the test.config
- dnappler container - the seqera wave one didn't work for me (arch issues)
  - replaced with the biocontainers one
- medaka - adjust the containers the : for the tag in the container was causing issues

Medaka

Error:
```bash
    File "/usr/local/lib/python3.12/argparse.py", line 2113, in consume_optional
      take_action(action, args, option_string)
    File "/usr/local/lib/python3.12/argparse.py", line 2018, in take_action
      action(self, namespace, argument_values, option_string)
    File "/usr/local/lib/python3.12/site-packages/medaka/medaka.py", line 39, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: sequence item 0: expected str instance, PosixPath found
```

I couldn't make it work, and I noticed that the param points to the $HOME folder?.
If users are required to download the medaka models, this should be stated in the docs (I couldn't find this).

Also, using the $HOME folder won't work with docker, not a huge problem but it does
hurt the portability (specially for cloud users). So I would change this default.